version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-121-32.eu-west-1.compute.amazonaws.com
            database: d7a424sg595ort
            schema: public
            user: zpreugyinhivwb
            password: 819fbbe3e181abe871890fee2191685ba0aea03878f2e9c5d4098ef3ad8ef8f0
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true